[PHP]
; Configuration for PHP 8.2
engine = On
short_open_tag = On
precision = 14
output_buffering = 4096
max_execution_time = 120
memory_limit = 512M
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED
display_errors = On
display_startup_errors = On
log_errors = On
error_log = "C:/end-server-main/logs/php/php_8.2_errors.log"
post_max_size = 256M
upload_max_filesize = 256M
max_file_uploads = 20

extension_dir = "C:/end-server-main/bin/php/php-8.2/ext"
extension=curl
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip

[CGI]
cgi.fix_pathinfo = 1
cgi.force_redirect = 0

[Date]
date.timezone = Asia/Seoul

[mail function]
SMTP = 127.0.0.1
smtp_port = 1025
