server {
    listen 80;
    server_name my-blog.test;
    root "C:/end-server-main/www/my-blog";
    index index.php index.html index.htm;
    charset utf-8;
    client_max_body_size 0;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /myadmin {
        alias "C:/end-server-main/bin/phpmyadmin/phpmyadmin-latest";
        index index.php index.html index.htm;

        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $request_filename;
            include        fastcgi_params;
        }
    }

    location /phpmyadmin {
        alias "C:/end-server-main/bin/phpmyadmin/phpmyadmin-3.1";
        index index.php index.html index.htm;

        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME $request_filename;
            include        fastcgi_params;
        }
    }


    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log "C:/end-server-main/logs/nginx/my-blog-access.log";
    error_log  "C:/end-server-main/logs/nginx/my-blog-error.log";

    location ~ \.php$ {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
