ServerRoot "C:/end-server-main/bin/apache"
Listen 80

LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule filter_module modules/mod_filter.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule version_module modules/mod_version.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so
LoadModule rewrite_module modules/mod_rewrite.so

ServerAdmin admin@localhost
ServerName localhost:80

<Directory />
    AllowOverride none
    Require all denied
</Directory>
LimitRequestBody 0

DocumentRoot "C:/end-server-main/www"
<Directory "C:/end-server-main/www">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
</Directory>

ProxyFCGISetEnvIf "true" SCRIPT_FILENAME "%{reqenv:DOCUMENT_ROOT}%{reqenv:SCRIPT_NAME}"

Alias /myadmin "C:/end-server-main/bin/phpmyadmin/phpmyadmin-latest"
<Directory "C:/end-server-main/bin/phpmyadmin/phpmyadmin-latest">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
    DirectoryIndex index.php index.html index.htm
    ProxyFCGISetEnvIf "reqenv('SCRIPT_NAME') =~ m#^/myadmin/(.*)$#" SCRIPT_FILENAME "C:/end-server-main/bin/phpmyadmin/phpmyadmin-latest/$1"
    ProxyFCGISetEnvIf "reqenv('SCRIPT_NAME') =~ m#^/myadmin/?$#" SCRIPT_FILENAME "C:/end-server-main/bin/phpmyadmin/phpmyadmin-latest/index.php"
    ProxyFCGISetEnvIf "reqenv('SCRIPT_FILENAME') =~ m#/$#" SCRIPT_FILENAME "C:/end-server-main/bin/phpmyadmin/phpmyadmin-latest/index.php"
</Directory>

Alias /phpmyadmin "C:/end-server-main/bin/phpmyadmin/phpmyadmin-3.1"
<Directory "C:/end-server-main/bin/phpmyadmin/phpmyadmin-3.1">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
    DirectoryIndex index.php index.html index.htm
    ProxyFCGISetEnvIf "reqenv('SCRIPT_NAME') =~ m#^/phpmyadmin/(.*)$#" SCRIPT_FILENAME "C:/end-server-main/bin/phpmyadmin/phpmyadmin-3.1/$1"
    ProxyFCGISetEnvIf "reqenv('SCRIPT_NAME') =~ m#^/phpmyadmin/?$#" SCRIPT_FILENAME "C:/end-server-main/bin/phpmyadmin/phpmyadmin-3.1/index.php"
    ProxyFCGISetEnvIf "reqenv('SCRIPT_FILENAME') =~ m#/$#" SCRIPT_FILENAME "C:/end-server-main/bin/phpmyadmin/phpmyadmin-3.1/index.php"
</Directory>

DirectoryIndex index.php index.html index.htm

<FilesMatch \.php$>
    SetHandler "proxy:fcgi://127.0.0.1:9000/"
</FilesMatch>

ErrorLog "C:/end-server-main/logs/apache/error.log"
LogLevel warn

<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    CustomLog "C:/end-server-main/logs/apache/access.log" common
</IfModule>

TypesConfig conf/mime.types

<VirtualHost *:80>
    ServerName localhost
    ServerAlias 127.0.0.1
    DocumentRoot "C:/end-server-main/www"
    <Directory "C:/end-server-main/www">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
        DirectoryIndex index.php index.html index.htm
    </Directory>
    ProxyFCGISetEnvIf "true" SCRIPT_FILENAME "%{reqenv:DOCUMENT_ROOT}%{reqenv:SCRIPT_NAME}"
</VirtualHost>

IncludeOptional "C:/end-server-main/config/apache/vhosts/*.conf"
