[mysqld]
; Configuration for MYSQL 5.1
port=3306
datadir="C:/end-server-main/data/db/mysql-5.1"
bind-address=127.0.0.1
max_allowed_packet=64M
default-character-set=utf8
character-set-server=utf8
collation-server=utf8_general_ci

[client]
port=3306
default-character-set=utf8mb4
