[mysqld]
; Configuration for MARIADB 10.11
port=3306
datadir="C:/end-server-main/data/db/mariadb-10.11"
bind-address=127.0.0.1
max_allowed_packet=64M
default_storage_engine=InnoDB
innodb_file_per_table=1
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

[client]
port=3306
default-character-set=utf8mb4
